name: macOS Dist

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Print versions
        run: bash scripts/print_versions.sh
      - name: Build dist
        run: make dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ImageToEPS-dist
          path: |
            ImageToEPS.dmg
            ImageToEPS-Setup.zip
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ImageToEPS.dmg
            ImageToEPS-Setup.zip
